source :rubygems

gem "sinatra"
gem "sinatra-flash"
gem "slim"
gem "faraday"
gem "faraday_middleware"
gem "omniauth"
gem "omniauth-appdotnet"
gem "curator", :git => "git://github.com/braintree/curator.git"
gem "mongo", "1.6.0"
gem "bson_ext", "1.6.0"
gem "nokogiri"
gem "thin"
gem "shotgun"
